//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ntier.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService2Soap")]
    public interface WebService2Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createPays", ReplyAction="*")]
        ntier.ServiceReference2.createPaysResponse createPays(ntier.ServiceReference2.createPaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createPays", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.createPaysResponse> createPaysAsync(ntier.ServiceReference2.createPaysRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorld2Result de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        ntier.ServiceReference2.HelloWorld2Response HelloWorld2(ntier.ServiceReference2.HelloWorld2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.HelloWorld2Response> HelloWorld2Async(ntier.ServiceReference2.HelloWorld2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPays", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.createPaysRequestBody Body;
        
        public createPaysRequest() {
        }
        
        public createPaysRequest(ntier.ServiceReference2.createPaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createPaysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        public createPaysRequestBody() {
        }
        
        public createPaysRequestBody(string nom) {
            this.nom = nom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.createPaysResponseBody Body;
        
        public createPaysResponse() {
        }
        
        public createPaysResponse(ntier.ServiceReference2.createPaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createPaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createPaysResult;
        
        public createPaysResponseBody() {
        }
        
        public createPaysResponseBody(int createPaysResult) {
            this.createPaysResult = createPaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.HelloWorld2RequestBody Body;
        
        public HelloWorld2Request() {
        }
        
        public HelloWorld2Request(ntier.ServiceReference2.HelloWorld2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorld2RequestBody {
        
        public HelloWorld2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2Response", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.HelloWorld2ResponseBody Body;
        
        public HelloWorld2Response() {
        }
        
        public HelloWorld2Response(ntier.ServiceReference2.HelloWorld2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorld2Result;
        
        public HelloWorld2ResponseBody() {
        }
        
        public HelloWorld2ResponseBody(string HelloWorld2Result) {
            this.HelloWorld2Result = HelloWorld2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : ntier.ServiceReference2.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<ntier.ServiceReference2.WebService2Soap>, ntier.ServiceReference2.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.createPaysResponse ntier.ServiceReference2.WebService2Soap.createPays(ntier.ServiceReference2.createPaysRequest request) {
            return base.Channel.createPays(request);
        }
        
        public int createPays(string nom) {
            ntier.ServiceReference2.createPaysRequest inValue = new ntier.ServiceReference2.createPaysRequest();
            inValue.Body = new ntier.ServiceReference2.createPaysRequestBody();
            inValue.Body.nom = nom;
            ntier.ServiceReference2.createPaysResponse retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).createPays(inValue);
            return retVal.Body.createPaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.createPaysResponse> ntier.ServiceReference2.WebService2Soap.createPaysAsync(ntier.ServiceReference2.createPaysRequest request) {
            return base.Channel.createPaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.createPaysResponse> createPaysAsync(string nom) {
            ntier.ServiceReference2.createPaysRequest inValue = new ntier.ServiceReference2.createPaysRequest();
            inValue.Body = new ntier.ServiceReference2.createPaysRequestBody();
            inValue.Body.nom = nom;
            return ((ntier.ServiceReference2.WebService2Soap)(this)).createPaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.HelloWorld2Response ntier.ServiceReference2.WebService2Soap.HelloWorld2(ntier.ServiceReference2.HelloWorld2Request request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2() {
            ntier.ServiceReference2.HelloWorld2Request inValue = new ntier.ServiceReference2.HelloWorld2Request();
            inValue.Body = new ntier.ServiceReference2.HelloWorld2RequestBody();
            ntier.ServiceReference2.HelloWorld2Response retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).HelloWorld2(inValue);
            return retVal.Body.HelloWorld2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.HelloWorld2Response> ntier.ServiceReference2.WebService2Soap.HelloWorld2Async(ntier.ServiceReference2.HelloWorld2Request request) {
            return base.Channel.HelloWorld2Async(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.HelloWorld2Response> HelloWorld2Async() {
            ntier.ServiceReference2.HelloWorld2Request inValue = new ntier.ServiceReference2.HelloWorld2Request();
            inValue.Body = new ntier.ServiceReference2.HelloWorld2RequestBody();
            return ((ntier.ServiceReference2.WebService2Soap)(this)).HelloWorld2Async(inValue);
        }
    }
}
