//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ntier.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CArticle", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CArticle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int Id_rubriqueField;
        
        private int PoidsField;
        
        private int Prix_unitaireField;
        
        private int Quantite_stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id_rubrique {
            get {
                return this.Id_rubriqueField;
            }
            set {
                if ((this.Id_rubriqueField.Equals(value) != true)) {
                    this.Id_rubriqueField = value;
                    this.RaisePropertyChanged("Id_rubrique");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Poids {
            get {
                return this.PoidsField;
            }
            set {
                if ((this.PoidsField.Equals(value) != true)) {
                    this.PoidsField = value;
                    this.RaisePropertyChanged("Poids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Prix_unitaire {
            get {
                return this.Prix_unitaireField;
            }
            set {
                if ((this.Prix_unitaireField.Equals(value) != true)) {
                    this.Prix_unitaireField = value;
                    this.RaisePropertyChanged("Prix_unitaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Quantite_stock {
            get {
                return this.Quantite_stockField;
            }
            set {
                if ((this.Quantite_stockField.Equals(value) != true)) {
                    this.Quantite_stockField = value;
                    this.RaisePropertyChanged("Quantite_stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRubrique", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CRubrique : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.Nullable<int> IDParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ntier.ServiceReference2.CRubrique[] RubriquesFillesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> IDParent {
            get {
                return this.IDParentField;
            }
            set {
                if ((this.IDParentField.Equals(value) != true)) {
                    this.IDParentField = value;
                    this.RaisePropertyChanged("IDParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ntier.ServiceReference2.CRubrique[] RubriquesFilles {
            get {
                return this.RubriquesFillesField;
            }
            set {
                if ((object.ReferenceEquals(this.RubriquesFillesField, value) != true)) {
                    this.RubriquesFillesField = value;
                    this.RaisePropertyChanged("RubriquesFilles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService2Soap")]
    public interface WebService2Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getAllArticlesResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllArticles", ReplyAction="*")]
        ntier.ServiceReference2.getAllArticlesResponse getAllArticles(ntier.ServiceReference2.getAllArticlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllArticles", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.getAllArticlesResponse> getAllArticlesAsync(ntier.ServiceReference2.getAllArticlesRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getAllArticlesFromRubriqueResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllArticlesFromRubrique", ReplyAction="*")]
        ntier.ServiceReference2.getAllArticlesFromRubriqueResponse getAllArticlesFromRubrique(ntier.ServiceReference2.getAllArticlesFromRubriqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllArticlesFromRubrique", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.getAllArticlesFromRubriqueResponse> getAllArticlesFromRubriqueAsync(ntier.ServiceReference2.getAllArticlesFromRubriqueRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément findArticleResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findArticle", ReplyAction="*")]
        ntier.ServiceReference2.findArticleResponse findArticle(ntier.ServiceReference2.findArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findArticle", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.findArticleResponse> findArticleAsync(ntier.ServiceReference2.findArticleRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createPays", ReplyAction="*")]
        ntier.ServiceReference2.createPaysResponse createPays(ntier.ServiceReference2.createPaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createPays", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.createPaysResponse> createPaysAsync(ntier.ServiceReference2.createPaysRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getAllRubriqueResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllRubrique", ReplyAction="*")]
        ntier.ServiceReference2.getAllRubriqueResponse getAllRubrique(ntier.ServiceReference2.getAllRubriqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllRubrique", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.getAllRubriqueResponse> getAllRubriqueAsync(ntier.ServiceReference2.getAllRubriqueRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createRubrique", ReplyAction="*")]
        ntier.ServiceReference2.createRubriqueResponse createRubrique(ntier.ServiceReference2.createRubriqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createRubrique", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.createRubriqueResponse> createRubriqueAsync(ntier.ServiceReference2.createRubriqueRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorld2Result de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        ntier.ServiceReference2.HelloWorld2Response HelloWorld2(ntier.ServiceReference2.HelloWorld2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<ntier.ServiceReference2.HelloWorld2Response> HelloWorld2Async(ntier.ServiceReference2.HelloWorld2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllArticlesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllArticles", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.getAllArticlesRequestBody Body;
        
        public getAllArticlesRequest() {
        }
        
        public getAllArticlesRequest(ntier.ServiceReference2.getAllArticlesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllArticlesRequestBody {
        
        public getAllArticlesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllArticlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllArticlesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.getAllArticlesResponseBody Body;
        
        public getAllArticlesResponse() {
        }
        
        public getAllArticlesResponse(ntier.ServiceReference2.getAllArticlesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllArticlesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ntier.ServiceReference2.CArticle[] getAllArticlesResult;
        
        public getAllArticlesResponseBody() {
        }
        
        public getAllArticlesResponseBody(ntier.ServiceReference2.CArticle[] getAllArticlesResult) {
            this.getAllArticlesResult = getAllArticlesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllArticlesFromRubriqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllArticlesFromRubrique", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.getAllArticlesFromRubriqueRequestBody Body;
        
        public getAllArticlesFromRubriqueRequest() {
        }
        
        public getAllArticlesFromRubriqueRequest(ntier.ServiceReference2.getAllArticlesFromRubriqueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllArticlesFromRubriqueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_rubrique;
        
        public getAllArticlesFromRubriqueRequestBody() {
        }
        
        public getAllArticlesFromRubriqueRequestBody(int id_rubrique) {
            this.id_rubrique = id_rubrique;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllArticlesFromRubriqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllArticlesFromRubriqueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.getAllArticlesFromRubriqueResponseBody Body;
        
        public getAllArticlesFromRubriqueResponse() {
        }
        
        public getAllArticlesFromRubriqueResponse(ntier.ServiceReference2.getAllArticlesFromRubriqueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllArticlesFromRubriqueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ntier.ServiceReference2.CArticle[] getAllArticlesFromRubriqueResult;
        
        public getAllArticlesFromRubriqueResponseBody() {
        }
        
        public getAllArticlesFromRubriqueResponseBody(ntier.ServiceReference2.CArticle[] getAllArticlesFromRubriqueResult) {
            this.getAllArticlesFromRubriqueResult = getAllArticlesFromRubriqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findArticleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findArticle", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.findArticleRequestBody Body;
        
        public findArticleRequest() {
        }
        
        public findArticleRequest(ntier.ServiceReference2.findArticleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findArticleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public findArticleRequestBody() {
        }
        
        public findArticleRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findArticleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findArticleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.findArticleResponseBody Body;
        
        public findArticleResponse() {
        }
        
        public findArticleResponse(ntier.ServiceReference2.findArticleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findArticleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ntier.ServiceReference2.CArticle findArticleResult;
        
        public findArticleResponseBody() {
        }
        
        public findArticleResponseBody(ntier.ServiceReference2.CArticle findArticleResult) {
            this.findArticleResult = findArticleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPays", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.createPaysRequestBody Body;
        
        public createPaysRequest() {
        }
        
        public createPaysRequest(ntier.ServiceReference2.createPaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createPaysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        public createPaysRequestBody() {
        }
        
        public createPaysRequestBody(string nom) {
            this.nom = nom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.createPaysResponseBody Body;
        
        public createPaysResponse() {
        }
        
        public createPaysResponse(ntier.ServiceReference2.createPaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createPaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createPaysResult;
        
        public createPaysResponseBody() {
        }
        
        public createPaysResponseBody(int createPaysResult) {
            this.createPaysResult = createPaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRubriqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllRubrique", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.getAllRubriqueRequestBody Body;
        
        public getAllRubriqueRequest() {
        }
        
        public getAllRubriqueRequest(ntier.ServiceReference2.getAllRubriqueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRubriqueRequestBody {
        
        public getAllRubriqueRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRubriqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllRubriqueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.getAllRubriqueResponseBody Body;
        
        public getAllRubriqueResponse() {
        }
        
        public getAllRubriqueResponse(ntier.ServiceReference2.getAllRubriqueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllRubriqueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ntier.ServiceReference2.CRubrique[] getAllRubriqueResult;
        
        public getAllRubriqueResponseBody() {
        }
        
        public getAllRubriqueResponseBody(ntier.ServiceReference2.CRubrique[] getAllRubriqueResult) {
            this.getAllRubriqueResult = getAllRubriqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createRubriqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createRubrique", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.createRubriqueRequestBody Body;
        
        public createRubriqueRequest() {
        }
        
        public createRubriqueRequest(ntier.ServiceReference2.createRubriqueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createRubriqueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ntier.ServiceReference2.CRubrique id_parent;
        
        public createRubriqueRequestBody() {
        }
        
        public createRubriqueRequestBody(string nom, string description, ntier.ServiceReference2.CRubrique id_parent) {
            this.nom = nom;
            this.description = description;
            this.id_parent = id_parent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createRubriqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createRubriqueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.createRubriqueResponseBody Body;
        
        public createRubriqueResponse() {
        }
        
        public createRubriqueResponse(ntier.ServiceReference2.createRubriqueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createRubriqueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createRubriqueResult;
        
        public createRubriqueResponseBody() {
        }
        
        public createRubriqueResponseBody(int createRubriqueResult) {
            this.createRubriqueResult = createRubriqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.HelloWorld2RequestBody Body;
        
        public HelloWorld2Request() {
        }
        
        public HelloWorld2Request(ntier.ServiceReference2.HelloWorld2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorld2RequestBody {
        
        public HelloWorld2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2Response", Namespace="http://tempuri.org/", Order=0)]
        public ntier.ServiceReference2.HelloWorld2ResponseBody Body;
        
        public HelloWorld2Response() {
        }
        
        public HelloWorld2Response(ntier.ServiceReference2.HelloWorld2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorld2Result;
        
        public HelloWorld2ResponseBody() {
        }
        
        public HelloWorld2ResponseBody(string HelloWorld2Result) {
            this.HelloWorld2Result = HelloWorld2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : ntier.ServiceReference2.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<ntier.ServiceReference2.WebService2Soap>, ntier.ServiceReference2.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.getAllArticlesResponse ntier.ServiceReference2.WebService2Soap.getAllArticles(ntier.ServiceReference2.getAllArticlesRequest request) {
            return base.Channel.getAllArticles(request);
        }
        
        public ntier.ServiceReference2.CArticle[] getAllArticles() {
            ntier.ServiceReference2.getAllArticlesRequest inValue = new ntier.ServiceReference2.getAllArticlesRequest();
            inValue.Body = new ntier.ServiceReference2.getAllArticlesRequestBody();
            ntier.ServiceReference2.getAllArticlesResponse retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).getAllArticles(inValue);
            return retVal.Body.getAllArticlesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.getAllArticlesResponse> ntier.ServiceReference2.WebService2Soap.getAllArticlesAsync(ntier.ServiceReference2.getAllArticlesRequest request) {
            return base.Channel.getAllArticlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.getAllArticlesResponse> getAllArticlesAsync() {
            ntier.ServiceReference2.getAllArticlesRequest inValue = new ntier.ServiceReference2.getAllArticlesRequest();
            inValue.Body = new ntier.ServiceReference2.getAllArticlesRequestBody();
            return ((ntier.ServiceReference2.WebService2Soap)(this)).getAllArticlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.getAllArticlesFromRubriqueResponse ntier.ServiceReference2.WebService2Soap.getAllArticlesFromRubrique(ntier.ServiceReference2.getAllArticlesFromRubriqueRequest request) {
            return base.Channel.getAllArticlesFromRubrique(request);
        }
        
        public ntier.ServiceReference2.CArticle[] getAllArticlesFromRubrique(int id_rubrique) {
            ntier.ServiceReference2.getAllArticlesFromRubriqueRequest inValue = new ntier.ServiceReference2.getAllArticlesFromRubriqueRequest();
            inValue.Body = new ntier.ServiceReference2.getAllArticlesFromRubriqueRequestBody();
            inValue.Body.id_rubrique = id_rubrique;
            ntier.ServiceReference2.getAllArticlesFromRubriqueResponse retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).getAllArticlesFromRubrique(inValue);
            return retVal.Body.getAllArticlesFromRubriqueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.getAllArticlesFromRubriqueResponse> ntier.ServiceReference2.WebService2Soap.getAllArticlesFromRubriqueAsync(ntier.ServiceReference2.getAllArticlesFromRubriqueRequest request) {
            return base.Channel.getAllArticlesFromRubriqueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.getAllArticlesFromRubriqueResponse> getAllArticlesFromRubriqueAsync(int id_rubrique) {
            ntier.ServiceReference2.getAllArticlesFromRubriqueRequest inValue = new ntier.ServiceReference2.getAllArticlesFromRubriqueRequest();
            inValue.Body = new ntier.ServiceReference2.getAllArticlesFromRubriqueRequestBody();
            inValue.Body.id_rubrique = id_rubrique;
            return ((ntier.ServiceReference2.WebService2Soap)(this)).getAllArticlesFromRubriqueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.findArticleResponse ntier.ServiceReference2.WebService2Soap.findArticle(ntier.ServiceReference2.findArticleRequest request) {
            return base.Channel.findArticle(request);
        }
        
        public ntier.ServiceReference2.CArticle findArticle(int id) {
            ntier.ServiceReference2.findArticleRequest inValue = new ntier.ServiceReference2.findArticleRequest();
            inValue.Body = new ntier.ServiceReference2.findArticleRequestBody();
            inValue.Body.id = id;
            ntier.ServiceReference2.findArticleResponse retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).findArticle(inValue);
            return retVal.Body.findArticleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.findArticleResponse> ntier.ServiceReference2.WebService2Soap.findArticleAsync(ntier.ServiceReference2.findArticleRequest request) {
            return base.Channel.findArticleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.findArticleResponse> findArticleAsync(int id) {
            ntier.ServiceReference2.findArticleRequest inValue = new ntier.ServiceReference2.findArticleRequest();
            inValue.Body = new ntier.ServiceReference2.findArticleRequestBody();
            inValue.Body.id = id;
            return ((ntier.ServiceReference2.WebService2Soap)(this)).findArticleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.createPaysResponse ntier.ServiceReference2.WebService2Soap.createPays(ntier.ServiceReference2.createPaysRequest request) {
            return base.Channel.createPays(request);
        }
        
        public int createPays(string nom) {
            ntier.ServiceReference2.createPaysRequest inValue = new ntier.ServiceReference2.createPaysRequest();
            inValue.Body = new ntier.ServiceReference2.createPaysRequestBody();
            inValue.Body.nom = nom;
            ntier.ServiceReference2.createPaysResponse retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).createPays(inValue);
            return retVal.Body.createPaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.createPaysResponse> ntier.ServiceReference2.WebService2Soap.createPaysAsync(ntier.ServiceReference2.createPaysRequest request) {
            return base.Channel.createPaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.createPaysResponse> createPaysAsync(string nom) {
            ntier.ServiceReference2.createPaysRequest inValue = new ntier.ServiceReference2.createPaysRequest();
            inValue.Body = new ntier.ServiceReference2.createPaysRequestBody();
            inValue.Body.nom = nom;
            return ((ntier.ServiceReference2.WebService2Soap)(this)).createPaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.getAllRubriqueResponse ntier.ServiceReference2.WebService2Soap.getAllRubrique(ntier.ServiceReference2.getAllRubriqueRequest request) {
            return base.Channel.getAllRubrique(request);
        }
        
        public ntier.ServiceReference2.CRubrique[] getAllRubrique() {
            ntier.ServiceReference2.getAllRubriqueRequest inValue = new ntier.ServiceReference2.getAllRubriqueRequest();
            inValue.Body = new ntier.ServiceReference2.getAllRubriqueRequestBody();
            ntier.ServiceReference2.getAllRubriqueResponse retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).getAllRubrique(inValue);
            return retVal.Body.getAllRubriqueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.getAllRubriqueResponse> ntier.ServiceReference2.WebService2Soap.getAllRubriqueAsync(ntier.ServiceReference2.getAllRubriqueRequest request) {
            return base.Channel.getAllRubriqueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.getAllRubriqueResponse> getAllRubriqueAsync() {
            ntier.ServiceReference2.getAllRubriqueRequest inValue = new ntier.ServiceReference2.getAllRubriqueRequest();
            inValue.Body = new ntier.ServiceReference2.getAllRubriqueRequestBody();
            return ((ntier.ServiceReference2.WebService2Soap)(this)).getAllRubriqueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.createRubriqueResponse ntier.ServiceReference2.WebService2Soap.createRubrique(ntier.ServiceReference2.createRubriqueRequest request) {
            return base.Channel.createRubrique(request);
        }
        
        public int createRubrique(string nom, string description, ntier.ServiceReference2.CRubrique id_parent) {
            ntier.ServiceReference2.createRubriqueRequest inValue = new ntier.ServiceReference2.createRubriqueRequest();
            inValue.Body = new ntier.ServiceReference2.createRubriqueRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.description = description;
            inValue.Body.id_parent = id_parent;
            ntier.ServiceReference2.createRubriqueResponse retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).createRubrique(inValue);
            return retVal.Body.createRubriqueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.createRubriqueResponse> ntier.ServiceReference2.WebService2Soap.createRubriqueAsync(ntier.ServiceReference2.createRubriqueRequest request) {
            return base.Channel.createRubriqueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.createRubriqueResponse> createRubriqueAsync(string nom, string description, ntier.ServiceReference2.CRubrique id_parent) {
            ntier.ServiceReference2.createRubriqueRequest inValue = new ntier.ServiceReference2.createRubriqueRequest();
            inValue.Body = new ntier.ServiceReference2.createRubriqueRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.description = description;
            inValue.Body.id_parent = id_parent;
            return ((ntier.ServiceReference2.WebService2Soap)(this)).createRubriqueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntier.ServiceReference2.HelloWorld2Response ntier.ServiceReference2.WebService2Soap.HelloWorld2(ntier.ServiceReference2.HelloWorld2Request request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2() {
            ntier.ServiceReference2.HelloWorld2Request inValue = new ntier.ServiceReference2.HelloWorld2Request();
            inValue.Body = new ntier.ServiceReference2.HelloWorld2RequestBody();
            ntier.ServiceReference2.HelloWorld2Response retVal = ((ntier.ServiceReference2.WebService2Soap)(this)).HelloWorld2(inValue);
            return retVal.Body.HelloWorld2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntier.ServiceReference2.HelloWorld2Response> ntier.ServiceReference2.WebService2Soap.HelloWorld2Async(ntier.ServiceReference2.HelloWorld2Request request) {
            return base.Channel.HelloWorld2Async(request);
        }
        
        public System.Threading.Tasks.Task<ntier.ServiceReference2.HelloWorld2Response> HelloWorld2Async() {
            ntier.ServiceReference2.HelloWorld2Request inValue = new ntier.ServiceReference2.HelloWorld2Request();
            inValue.Body = new ntier.ServiceReference2.HelloWorld2RequestBody();
            return ((ntier.ServiceReference2.WebService2Soap)(this)).HelloWorld2Async(inValue);
        }
    }
}
